[package]
name = "supershell"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
serde_json = "1.0.145"
serde_yml = "0.0.12"
crossterm = "0.29.0"
textwrap = "0.16.2"
directories = "6.0.0"
